project_id = "scfgwjnhhfdmvezhkipt"

[functions.track-analytics]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.get-page]
verify_jwt = false

[functions.get-marketing-data]
verify_jwt = false
